compiler: gcc
dist: xenial

script:
    - gcc merlict-c89-test.c -o merlict-c89-test -std=c89 -lm -Wall -pedantic
    - ./merlict-c89-test
    - g++ merlict-c89-test.c -o merlict-c89-test -lm -Wall -pedantic
    - ./merlict-c89-test
