/* Copyright 2018-2020 Sebastian Achim Mueller */
#ifndef MERLICT_C89_CORSIKA_VERSION_H_
#define MERLICT_C89_CORSIKA_VERSION_H_

#define MLI_CORSIKA_VERSION_MAYOR 0
#define MLI_CORSIKA_VERSION_MINOR 0
#define MLI_CORSIKA_VERSION_PATCH 0

#endif
